### ISSUE TITLE
migration broken with latest mysql migration changes

### ISSUE THREAD

**Issue by notandy** [sapcc/asr1k-neutron-l3#31]
```Running upgrade for neutron ...
OK
Traceback (most recent call last):
  File "/var/lib/openstack/bin/neutron-db-manage", line 8, in <module>
    sys.exit(main())
  File "/var/lib/openstack/local/lib/python2.7/site-packages/neutron/db/migration/cli.py", line 652, in main
    return_val |= bool(CONF.command.func(config, CONF.command.name))
  File "/var/lib/openstack/local/lib/python2.7/site-packages/neutron/db/migration/cli.py", line 171, in do_upgrade
    run_sanity_checks(config, revision)
  File "/var/lib/openstack/local/lib/python2.7/site-packages/neutron/db/migration/cli.py", line 636, in run_sanity_checks
    script_dir.run_env()
  File "/var/lib/openstack/local/lib/python2.7/site-packages/alembic/script/base.py", line 425, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/var/lib/openstack/local/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/var/lib/openstack/local/lib/python2.7/site-packages/alembic/util/compat.py", line 141, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "/var/lib/openstack/src/asr1k-neutron-l3/asr1k_neutron_l3/db/migration/alembic_migrations/env.py", line 127, in <module>
    run_migrations_online()
  File "/var/lib/openstack/src/asr1k-neutron-l3/asr1k_neutron_l3/db/migration/alembic_migrations/env.py", line 118, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/var/lib/openstack/local/lib/python2.7/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/var/lib/openstack/local/lib/python2.7/site-packages/alembic/runtime/migration.py", line 321, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/var/lib/openstack/local/lib/python2.7/site-packages/neutron/db/migration/cli.py", line 627, in check_sanity
    revision, rev, implicit_base=True):
  File "/var/lib/openstack/local/lib/python2.7/site-packages/alembic/script/revision.py", line 698, in _iterate_revisions
    select_for_downgrade and requested_lowers
  File "/var/lib/openstack/local/lib/python2.7/site-packages/alembic/script/revision.py", line 694, in <genexpr>
    rev.revision for rev
  File "/var/lib/openstack/local/lib/python2.7/site-packages/alembic/script/revision.py", line 631, in _iterate_related_revisions
    ", ".join(r.revision for r in overlaps)
alembic.script.revision.RevisionError: Requested revision 5678db342f9 overlaps with other requested revisions 6777c66483ab```

**Comment by galkindmitrii** [comment]
Fixed with: https://github.com/sapcc/asr1k-neutron-l3/commit/ea2f81e6c081032a5d39590f779467665cddc1db
